### PR TITLE
Made Webhooks more Easily Configurable

### PR DESCRIPTION
**Pull request by couldbehenry**
Made it so the webhook url's must only be put in webhooks.json and not in the actual file to make it more easy for configuration

### CODE REVIEW

**Comment by CorwinDev** [comment]
Thanks, but what did you do to [src/commands/developers/args.js](https://github.com/CorwinDev/Discord-Bot/pull/79/files#diff-3ef59d8344e2becdce8b30377e14a273f2308eeff5da5ecc2d89a50dcd586f87) ?

**Comment by HenryCpr** [comment]
I just took off the spaces from the images as it didn't work for me with the spaces and also malfunctioned on replit.

**Comment by CorwinDev** [comment]
That whole url isn't even working so, if you revert that one ill merge it :)

**Comment by HenryCpr** [comment]
Will do that rn and just realized I deleted a essential webhook the startLogs one so I'll re-add that too.

**Comment by HenryCpr** [comment]
Fixed it

**Comment by CorwinDev** [comment]
And one thing more, add it to bot.js and index.js 🙂

**Comment by HenryCpr** [comment]
I'm sorry can you be more specific? I'm kinda lost in ur words lmao

**Comment by HenryCpr** [comment]
Do you want `startLogs` to be configured to .env?

**Comment by CorwinDev** [comment]
https://github.com/CorwinDev/Discord-Bot/blob/e9aa9cabaef3cfe94d802dc48c5356ccaedaa2a1/src/bot.js#LL116C20-L116C20 
and https://github.com/CorwinDev/Discord-Bot/blob/e9aa9cabaef3cfe94d802dc48c5356ccaedaa2a1/src/index.js#L18

**Comment by HenryCpr** [comment]
Ahh i see I'll do it

**Pull request merged**
